AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'db/migrate/*'
  SuggestExtensions: false

Metrics/BlockLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Enabled: false

Layout/IndentationWidth:
  Width: 2

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false  # Disable documentation comments globally
