name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  # Run tests for the Ruby on Rails application
  test:
    name: Run Rails Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ecommerce_api_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Specify the version of Ruby
          bundler-cache: true

      - name: Install Dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Set up the database
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load
      
      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Run Tests
        env:
          RAILS_ENV: test
        run: bundle exec rspec

  # Security scan using Bundler Audit for Ruby dependencies
  security:
    name: Run Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Specify the version of Ruby

      - name: Install Dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run Bundler Audit
        run: |
          gem install bundler-audit
          bundle audit check --update
