name: Rubocop Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Adjust this to match your Ruby version
          bundler-cache: true # Caches bundle install

      - name: Install dependencies
        run: |
          bundle install

      - name: Run Rubocop
        run: |
          bundle exec rubocop
